sprint2/2426
Mobility-Solutions/Transportify pull request #24
Opened 2019-11-16 15:58 UTC by andresen1998

UT 2426 - Registrar usuario y autenticación

2019-11-16 20:52 UTC, Peldelnas commented
Se producen excepciones que no están controladas tanto al registrarse como iniciar sesión. Algunas de ellas son:

- Email ya en uso (al registrar)

- Formato de email inválido

- Usuario no encontrado (al logear)

- Contraseña incorrecta _o el usuario no la tiene_ (al logear)

También no hay indicativo real en la aplicación de que un usuario se haya logeado _salvo de que es el único caso en el que la aplicación no peta_

El resto de PAs pasan, exceptuando dos a la espera de ver si se eliminan y se reespecifica la UT

2019-11-16 20:54 UTC, Peldelnas requested changes
Se producen excepciones que no están controladas tanto al registrarse como iniciar sesión. Algunas de ellas son:

   - Email ya en uso (al registrar)

   - Formato de email inválido

   - Usuario no encontrado (al logear)

  -  Contraseña incorrecta o el usuario no la tiene (al logear)

También no hay indicativo real en la aplicación de que un usuario se haya logeado salvo de que es el único caso en el que la aplicación no peta

El resto de PAs pasan, exceptuando dos a la espera de ver si se eliminan y se reespecifica la UT

2019-11-17 13:03 UTC, Peldelnas requested changes
Siguen dándose diversas excepciones no controladas como:

- Email ya en uso (al registrar)

- Usuario no encontrado (al logear)

- Contraseña incorrecta o el usuario no la tiene (al logear)

Continúa sin haber indicativo en la app de que el usuario se haya logeado después de introducir sus credenciales.

2019-11-18 14:23 UTC, algono commented
@Peldelnas revisa la pull request #26 antes de aprobar esta

2019-11-18 18:21 UTC, Peldelnas approved these changes
ok

2019-11-18 18:22 UTC, merged