Sprint3/2867
Mobility-Solutions/Transportify pull request #48
Opened 2019-12-06 17:51 UTC by UxxeR

2019-12-06 20:20 UTC, algono requested changes
Cambios necesarios:
- Si creas una incidencia, sales de la ventana de seguimiento y vuelves a entrar, la incidencia que habías creado desaparece
- Al abrir el teclado para escribir el texto de la incidencia aparece un error de overflow de algún widget. También ocurre al abrir el teclado para indicar las horas de retraso.

Sugerencias:
- Estaría bien una forma de modificar y/o eliminar una incidencia. Por lo menos eliminarla, si modificar es muy complicado no hace falta, pero eliminarla me parece importante.

2019-12-06 20:24 UTC, UxxeR commented
> * Si creas una incidencia, sales de la ventana de seguimiento y vuelves a entrar, la incidencia que habías creado desaparece
> * Estaría bien una forma de modificar y/o eliminar una incidencia. Por lo menos eliminarla, si modificar es muy complicado no hace falta, pero eliminarla me parece importante.

Desaparece porque Actividad no esta acabada y no se le pasa un paquete de la base de datos si no que se crea un nuevo paquete en inicio.
Respecto a modificar/eliminar no esta especificado en la ut, quizá seria mejor crear una ut de mejora.

2019-12-06 20:29 UTC, algono commented
> Desaparece porque Actividad no esta acabada y no se le pasa un paquete de la base de datos si no que se crea un nuevo paquete en inicio.

Vale, tiene sentido. En ese caso, la pull request quedará cerrada hasta que la UT de actividad termine y sea mergeada, para evitar que esta UT se mergee antes de hora.

> Respecto a modificar/eliminar no esta especificado en la ut, quizá seria mejor crear una ut de mejora.

De acuerdo, veo bien la UT de mejora, la crearé en el backlog y si alguien está ocioso la puede meter al sprint.

2019-12-06 20:32 UTC, algono commented
He editado los cambios para añadir este bug:
>Al abrir el teclado para escribir el texto de la incidencia aparece un error de overflow de algún widget. También ocurre al abrir el teclado para indicar las horas de retraso.
Me había olvidado de él, puede que no sea el más importante pero estaría bien echarle un vistazo por si acaso.

2019-12-06 20:38 UTC, algono commented
Tal vez tenga más sentido dejarla abierta.

2019-12-06 20:45 UTC, algono commented
> > Respecto a modificar/eliminar no esta especificado en la ut, quizá seria mejor crear una ut de mejora.
> 
> De acuerdo, veo bien la UT de mejora, la crearé en el backlog y si alguien está ocioso la puede meter al sprint.

Al final he creado una UT de mejora (2942) en el backlog, llamada "Cancelar incidencias".
En vez de modificar o eliminar incidencias, he pensado que sería mejor idea poder cancelar una incidencia pero que quede registrada, solo que en un tono grisáceo que indique que está cancelada, y que el retraso deje de afectar a la barra de progreso.

La idea es evitar que los transportistas borren las incidencias más tarde para evitar que se vean y pueda afectar a su reputación (similar a las pull requests en GitHub)

Sé que no afecta a esta UT, pero como la idea ha surgido de aquí, lo dejo por escrito.

2019-12-07 11:32 UTC, algono commented
Fix para el bottomnavigationbar no subiendo cuando abres el teclado:
https://github.com/flutter/flutter/issues/13339

2019-12-07 11:35 UTC, algono reviewed
Una cuestión: ¿Por qué hay varios textos metidos en un TextField con enabled a false? ¿Es para poder ponerle la decoration?

2019-12-07 12:13 UTC, UxxeR commented
> Una cuestión: ¿Por qué hay varios textos metidos en un TextField con enabled a false? ¿Es para poder ponerle la decoration?

Si

2019-12-08 12:46 UTC, algono approved these changes
Para adelante, hasta que acabe la UT de actividad (2802)

2019-12-08 20:03 UTC, merged